version: '2'
services:
  web:
    build: .
    ports:
      - "5000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/opt/webapp
      - name: nginx-dir
        emptyDir: { }
      - name: nginx-empty
        emptyDir: { }
      - name: nginx-run
        emptyDir: { }

    volumeMount:
      - mountPath: /etc/nginx/conf.d/
        name: nginx-dir
      - mountPath: /var/cache/nginx/client_temp
        name: nginx-empty
      - mountPath: /var/run/
        name: nginx-run
  db:
    image: nginx:latest
    ports:
      - "8083:80"


