version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
      - 443:443
    volumes:
      - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/ssl:/ssl/
