version: '2'
services:
  web:
    build: .
    ports:
      - "5000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/opt/webapp
  db:
    image: nginx:latest
    ports:
      - "8083:80"


