version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./index.html:/opt/webapp
  db:
    image: nginx:latest
    ports:
      - "8083:80"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
