pipeline {
  agent any
  tools {
    maven 'maven-3.6.3' 
  }
  stages {
    stage ('Build') {
      steps {
        bat 'mvn -f DevOpsProject/pom.xml clean install package'

      }
    }
    stage ('Deploy') {
      steps {
        script {
          deploy adapters: [tomcat9(credentialsId: 'tomcat_credential', path: '', url: 'http://localhost:8088/DevOpsProject')], contextPath: '/DevOpsProject', onFailure: false, war: 'webapp/target/*.war' 
        }
      }
    }
  }
}